### ISSUE TITLE
Are there some problems with using max overlap of gold answer?

### ISSUE THREAD

**Issue by SparkJiao** [momohuang/FlowQA#3]
Well, I calculated the final F1 score of all the extracted answers with max F1 of gold answers and it's 89.
So do you think it's may cause bad performance by using them as supervised? I don't know how to use the span_text and input_text now. Thanks!

**Comment by hsinyuan-huang** [comment]
Hi,

Currently, I am using this setting because my model output is always a span in the text (when it's not yes, no, or no answer). I think using a good text generation approach (that is not just a span in the text) would certainly give you a boost in performance. However, generation is much harder, so to what degree would you gain is unclear.

For example, to correctly generate some portion of the answer, some counting needs to be done (the answer to the question is a number, but there is no number in the context).

**Comment by SparkJiao** [comment]
Very appreciate to your reply!
